# Generated by Django 2.1.2 on 2018-10-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('notes', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('secrets', models.CharField(max_length=100)),
            ],
        ),
    ]
