# Generated by Django 2.1.2 on 2018-10-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
